Repository labring/devbox-websocket-tunnel, pull requests merged in 2024-12, with the labels that each got.

#1 feat: init
  .github/workflows/build.yml
  .gitignore
  README.md
  client/go.mod
  client/go.sum
  client/main.go
  client/wsd.go
  go.mod
  go.sum
  go.work
  go.work.sum
  server/Dockerfile
  server/go.mod
  server/go.sum
  server/main.go
  server/ws.go
  server/wsh.go
Labels: size/XL

#3 feat: tls skip verify
  README.md
  client/main.go
  client/wsd.go
Labels: size/S

#2 feat: add auto shutdown
  .gitignore
  go.work.sum
  server/healthy.go
  server/main.go
  server/wsh.go
Labels: size/L

#5 feat: release workflow
  .github/workflows/release.yml
Labels: size/M

#6 fix: latest tag
  .github/workflows/release.yml
Labels: size/XS
